using Data.Model.Entities.organization;
using Data.Model.Request.reportes;
using Data.Model.Response.reportes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Repositories.IContractsRepo.reportes
{
    public interface IOrdenreporteRepository : IRepository<OrdenReporte>
    {
        IEnumerable<serviceReportResponse> GetServiceReport(string id);
        IEnumerable<diagnosticRepositoryListResponse> GetAptitudeCertificateRefactNew(string id);
        IEnumerable<diagnosticRepositoryList2Response> GetAptitudeCertificateRefactNew2(string id);
        IEnumerable<diagnosticRepositoryList3Response> GetAptitudeCertificateRefactNew3(string id);
        IEnumerable<ostioCoimolacheResponse> GetReportOsteoCoimalache(filtroServicioComponenteRequest obj);
        IEnumerable<serviceComponentFieldValuesListResponse> GetValoresComponente(filtroServicioComponenteRequest obj);
        IEnumerable<reportToxicologicoResponse> GetReportToxicologico(filtroServicioComponenteRequest obj);
        IEnumerable<devolverComponentesConcatenadosResponse> DevolverComponentesConcatenados(string id);
        IEnumerable<devolverComponentesConcatenadosResponse> GetDevolverComponentesLaboratorioConcatenados(filtroServicioComponenteRequest obj);
        IEnumerable<reportConsentimientoResponse> GetReportConsentimiento(string id);
        IEnumerable<obtenerIdsImporacionResponse> ObtenerIdsParaImportacionExcel(filtroServicioYCategoriaRequest obj);
        IEnumerable<organizationDtoResponse> GetInfoMedicalCenter(string id);
        IEnumerable<serviceComponentFieldValuesListUserControlResponse> GetValoresComponentesUserControl(filtroServicioComponenteRequest obj);
        IEnumerable<osteomuscularNuevoResponse> GetReportOsteoMuscularNuevo(filtroServicioComponenteRequest obj);
        IEnumerable<recomendationsResponse> GetRecomendationByServiceIdAndComponentConcatec(filtroServicioComponenteRequest obj);
        IEnumerable<diseasesNameResponse> GetDisgnosticsCIE10ByServiceIdAndComponentConcatec(filtroServicioComponenteRequest obj);
        IEnumerable<serviceComponentFieldValuesListUserControlResponse> ValoresComponenteOdontograma1(filtroServicioComponenteRequest obj);
        IEnumerable<ucOsteoResponse> ReporteOsteomuscular(filtroServicioComponenteRequest obj);
        IEnumerable<musculoesqueleticoResponse> GetMusculoEsqueletico(filtroServicioComponenteRequest obj);
        IEnumerable<capeResponse> GetCAPE(string id);
        IEnumerable<recommendationNameResponse> GetConcatenateRecommendationByService_New_2(string id);
        IEnumerable<restrictionsNameResponse> GetConcatenateRestrictionByServiceConcatecDx(string id);
        IEnumerable<reportHistoriaOcupacionalResponse> GetReportHistoriaOcupacional(string id);
        IEnumerable<reportFuncionesVitalesResponse> GetReportFuncionesVitales(filtroServicioComponenteRequest obj);
        IEnumerable<reportAntropometriaResponse> GetReportAntropometria(filtroServicioComponenteRequest obj);
        IEnumerable<alturaEstructuralResponse> GetAlturaEstructural(filtroServicioComponenteRequest obj);
        IEnumerable<reportEstudioElectrocardiograficoResponse> GetReportEstudioElectrocardiografico(filtroServicioComponenteRequest obj);
        IEnumerable<diseasesNameResponse> GetDiagnosticByServiceIdAndComponent(filtroServicioComponenteRequest obj);
        IEnumerable<recommendationResponse> GetRecommendationByServiceIdAndComponent(filtroServicioComponenteRequest obj);
        IEnumerable<reportElectroGoldResponse> GetReportElectroGold(filtroServicioComponenteRequest obj);
        IEnumerable<valoresComponenteOdontogramaResponse> GetValoresComponenteOdontograma(filtroServicioComponentePathRequest obj);
        IEnumerable<serviceComponentFieldValuesListUserControlResponse> GetValoresComponenteOdontogramaValue1(filtroServicioComponenteRequest obj);
        IEnumerable<serviceComponentFieldValuesListUserControlResponse> GetValoresComponenteOdontogramaAusente(filtroServicioComponentePathRequest obj);
        IEnumerable<listValueComponentResponse> GetListValueComponent(string id);
        IEnumerable<reportOdontogramaResponse> GetReportOdontograma(filtroServicioComponenteRequest obj);
        IEnumerable<diagnosticrepositorybycomponent1Response> GetDiagnosticRepositoryByComponent1(filtroServicioComponenteRequest obj);
        IEnumerable<diagnosticrepositorybycomponent2Response> GetDiagnosticRepositoryByComponent2(filtroServicioComponenteRequest obj);
        IEnumerable<diagnosticrepositorybycomponent3Response> GetDiagnosticRepositoryByComponent3(filtroServicioComponenteRequest obj);
        IEnumerable<reportAudiometriaResponse> GetReportAudiometria(filtroServicioComponenteRequest obj);
        IEnumerable<diseasesNameResponse> GetDiagnosticByServiceIdAndCategoryId(filtroServicioYCategoriaRequest obj);
        IEnumerable<restrictionsNameResponse> ConcatenateRecomendacionesByCategoria(filtroServicioYCategoriaRequest obj);
        IEnumerable<fichaPsicologicaOcupacionalResponse> GetFichaPsicologicaOcupacional(string id);
        IEnumerable<reportRadiologicoResponse> GetReportRadiologico(filtroServicioComponenteRequest obj);
        IEnumerable<reportInformeRadiograficoResponse> GetReportInformeRadiografico(filtroServicioComponenteRequest obj);
        IEnumerable<reportCuestionarioEspirometriaResponse> GetReportCuestionarioEspirometria(filtroServicioComponenteRequest obj);
        IEnumerable<obtenerFirmaMedicoExamenResponse> GetObtenerFirmaMedicoExamen(filtroServiceComponentComponent obj);
        IEnumerable<reportCuestionarioNordicoResponse> GetReportCuestionarioNordico(filtroServicioComponenteRequest obj);
        IEnumerable<cAPSDResponse> GetCAPSD(string id);
        IEnumerable<recommendationNameResponse> GetConcatenateRecommendation(string id);
        IEnumerable<historiaClinicaPsicologicaResponse> GetHistoriaClinicaPsicologica(filtroServicioComponenteRequest obj);
        IEnumerable<reporteLumboSacaResponse> GetReporteLumboSaca(filtroServicioComponenteRequest obj);
        IEnumerable<reportCocainaMarihuanaResponse> GetReportCocainaMarihuana(filtroServicioComponenteRequest obj);
        IEnumerable<audiometriaCoimolacheResponse> GetAudiometriaCoimolache(filtroServicioComponenteRequest obj);
        pacientreportepsResponse GetPacientReportEPS(string id);
        IEnumerable<historyReportResponse> GetHistoryReport(string id);
        IEnumerable<familyMedicalAntecedentsReportResponse> GetFamilyMedicalAntecedentsReport(string id);
        IEnumerable<personMedicalHistoryReportResponse> GetPersonMedicalHistoryReport(string id);
        IEnumerable<noxiousHabitsReportResponse> GetNoxiousHabitsReport(string id);
        IEnumerable<valoresExamenComponeteResponse> GetValoresExamenComponete(filtroServicioComponenteRequest obj);
        IEnumerable<diseasesNameResponse> GetDiagnosticForAudiometria(filtroServicioComponenteRequest obj);
        IEnumerable<serviceDisgnosticsReportsResponse> GetServiceDisgnosticsReports(string id);
        IEnumerable<restrictionsNameResponse> GetConcatenateRestriction(string id);
        IEnumerable<serviceRecommendationByServiceIdResponse> GetServiceRecommendationByServiceId(string id);
        IEnumerable<serviceComponentsReportSCResponse> GetServiceComponentsReportSC(string id);
        IEnumerable<serviceComponentsReportCResponse> GetServiceComponentsReportC(string id);
        IEnumerable<valoresComponenteAmcResponse> GetValoresComponenteAMC(filtroServicioYCategoriaRequest obj);
        IEnumerable<serviceComponentsReport_New312Response> GetServiceComponentsReport_New312(string id);
        IEnumerable<serviceComponentDiagnosticsReportResponse> GetServiceComponentDiagnosticsReport(filtroServicioComponenteRequest obj);
        IEnumerable<serviceShortResponse> GetServiceShort(string id);
        IEnumerable<anamnesisReportResponse> GetAnamnesisReport(filtroServiceComponentComponent obj);
        IEnumerable<servicecomponentconclusionesdxserviceidreportResponse> GetServiceComponentConclusionesDxServiceIdReport(string id);
        IEnumerable<servicerecommendationbydiagnosticrepositoryidreportResponse> GetServiceRecommendationByDiagnosticRepositoryIdReport(string id);
        IEnumerable<serviceRestrictionByDiagnosticrepositoryidreport> GetServiceRestrictionByDiagnosticRepositoryIdReport(string id);
        IEnumerable<doctoPhisicalexamResponse> GetDoctoPhisicalExam(filtroServicioComponenteRequest obj);
        IEnumerable<serviceComponentConclusionesDxServiceidReport_todosResponse> GetServiceComponentConclusionesDxServiceIdReport_TODOS(string id);
        IEnumerable<restrictionsNameResponse> GetRestrictionByServiceId(string id);
        IEnumerable<valoresComponente_ObservadoAmcResponse> GetValoresComponente_ObservadoAMC(filtroServicioComponenteRequest obj);
        IEnumerable<nombremedicolabResponse> GetNombreMedicoLab(string id);
        IEnumerable<nombreEmpresaLabResponse> GetNombreEmpresaLab(string id);
        devolverDatosPacienteResponse DevolverDatosPaciente(string id);
        IEnumerable<devolverDatosUsuarioGraboExamenResponse> GetDevolverDatosUsuarioGraboExamen(filtroServicioYCategoriaRequest obj);
        IEnumerable<antecedentesOcupacionalesResponse> AntecedentesOcupacionales(string id);
        IEnumerable<antecedentesMedicosResponse> AntecedentesmEDICOS(string id);
        IEnumerable<firmaMedicosResponse> GetFirmaMedicos(int id);
        IEnumerable<informacion_OtrosExamenes_MSResponse> GetInformacion_OtrosExamenes_MS(string id);
        IEnumerable<pacientReportEpsFirmamedicoOcupacionalResponse> GetPacientReportEPSFirmaMedicoOcupacional(string id);
        IEnumerable<recommendationNameResponse> GetListRecommendationByServiceIdAndComponent(filtroServicioComponenteRequest obj);
        IEnumerable<devolverAptitudResponse> GetDevolverAptitud(string id);
        IEnumerable<historyReportResponse> GetHistoryReportA(string id);
        IEnumerable<historyReportResponse> GetHistoryReportB(string id);
        LogoEmpresaResponse GetLogoEmpresa(string id);
        IEnumerable<informacion_LaboratorioResponse> GetInformacion_Laboratorio(string id);
        IEnumerable<informacion_Otrosexamenes_NewResponse> GetInformacion_OtrosExamenes_New(string id);
        IEnumerable<serviceComponentsReport_Newlab_1Response> GetServiceComponentsReport_NewLab_1(string id);
        IEnumerable<serviceComponentsReport_Newlab_2Response> GetServiceComponentsReport_NewLab_2(string id);
        IEnumerable<devolverAntecedentesPersonalesResponse> GetDevolverAntecedentesPersonales(string id);
        IEnumerable<aptitudMedicoServicioResponse> GetAptitudMedicoServicio(string id);
        organizationDtoResponseN GetInfoMedicalCenterN(string id);
        IEnumerable<serviceComponentsReport_DxListResponse> GetServiceComponentsReport_DxList(filtroServicioComponenteRequest obj);
        IEnumerable<reportCuestionarioEspirometriaAllResponse> GetReportCuestionarioEspirometria_ALL(filtroServicioComponenteRequest obj);
    }
}
